### ISSUE TITLE
LinkRest to AgREST rebranding: Rename packages and files

### ISSUE THREAD

**Issue by vyarmolovich** [agrestio/agrest#331]
We are [rebranding the project](https://groups.google.com/forum/?#!topic/linkrest-user/RvrkAyf775o) to be called AgREST. Need to change the code modules.

1. The prefix of the package names should be changed from `com.nhl.link.rest` to `io.agrest`
2. The existing prefix of some class names should be changed from **Lr** to **Ag** eg.
```
LrRequest ==> AgRequest
```

**Comment by andrus** [comment]
Closing. The main work has been done. We need to update the docs, but this will be tracked under #333
