### ISSUE TITLE
Protocol Enhancement: 'include\exclude' parameters should take an array of values

### ISSUE THREAD

**Issue by vyarmolovich** [agrestio/agrest#358]
### Objective:
The idea is to reduce a number of **include** parameters in an Agrest request.

### Current State:
At the moment **include** parameter allows two ways of initialization:
 1. Initialized by a single value (the simple **include**):
`include=id & include=articles.title`  

 2. Initialized by values in JSON format (the advanced **include**): 
`include={ "path" : "articles", "cayenneExp" : "title like '%Agrest%'", "sort" : "title" }`

### Acceptance Criteria:
- **include** and **exclude** parameters  have ability to take an array of values:
`include=[ "id", "name" ]`

- The array can contain both the simple **include** and the advanced **include** values
`include=[ "id", "articles.title", { "path" : "articles", "cayenneExp" : "title like '%Agrest%'" } ]`

- Attributes of a related entity can be presented as an inner array in JSON format:
`include=[ "id", "name", { "articles" : [ "title", "body" ] } ]` 

- The related entity can be specified as a path value:
`include=[ "id", "name", { "articles.categories" : [ "id", "name" ] } ]`

- The advanced include can contain the array of **include** values:
`include={ "path" : "articles", "sort" : "title", "include" : ["title", {"categories" : ["id", "name"]}] }`

**Comment by andrus** [comment]
Implementation is committed. Also need to add the protocol docs

**Comment by vyarmolovich** [comment]
Docs were updated.
