### ISSUE TITLE
Add support for Case Insensitive Sorting

### ISSUE THREAD

**Issue by sullyslegacy** [agrestio/agrest#428]

**Comment by andrus** [comment]
As this affects Agrest protocol (albeit in a fully backwards-compatible manner), I guess this warrants a bit more description. So we are adding two new sort `dir` parameters to allow for case-insensitive sorting in all cases where sorting is supported. 

In addition to `ASC` and `DESC` sorting, let's add `ASC_CI` and `DESC_CI` directions that will instruct Agrest server to sort data in a case-insensitive order using collation rules decided by the server and outside the Agrest protocol
