### ISSUE TITLE
Implementing Id encoder / decoder for 'compound' ID entities

### ISSUE THREAD

**Issue by andrus** [agrestio/agrest#50]
We need a pluggable mechanism for semi-opaque ID encoding/decoding similar to cayenne-lifecycle IdCoder [1]. It should be compatible with the current implicit ID encoding. I.e. single column IDs should render as is. Multi-column should be concatenated with separator. Unlike IdCoder we don't need to include entity name in the encoded id. Also we probably need to implement some kind of escaping scheme to tell separators from ID bodies.

[1] https://github.com/apache/cayenne/blob/master/cayenne-lifecycle/src/main/java/org/apache/cayenne/lifecycle/id/IdCoder.java

**Comment by atomashpolskiy** [comment]
Did you think about using query parameters for resource identification? It's definitely the way [it's meant to be working in web apps](http://tools.ietf.org/html/rfc3986#section-3.4). And for hierarchical URLs that represent relationships matrix parameters seem like a way to go. Then you'll only need to extend LinkRestService interface with methods that allow compound IDs, say Map<String,Object>.

**Comment by andrus** [comment]
Yeah, some kind of Map structure might be one option. One caveat with it though is that more often than not a client can not easily guess the key names in ID map. E.g. in Cayenne those are mapped as db: attributes and are not a part of the object definition. So this may also require some implicit assumptions (client knowledge of DB attributes, or some ordering of ID values). 

So one possible ID "codec" might be a map codec with keys being obj or db expressions. And another maybe the one that we discussed - a codec that generates/consumes a single value. The later codec will be more opaque, but also compact and can be used in the path.

**Comment by atomashpolskiy** [comment]
Client does not need to know anything; mapping of URL parameters onto map of IDs is performed in back-end resource method. And there you have your model with statically accessible PK column names, which (I guess) you could use to reconstruct ObjectId.

My idea was that given URL:
http://whatever.com/myapp/person;name=Jack;surname=Doe/friends?sex=f&min-age=18

Backend programmer will need to create a resource:
```java
@Path("person")
public class Person {
    @GET
    @Path("friends")
    public DataResponse<Person> getFriends(
            @MatrixParam("name") String name,
            @MatrixParam("surname") String surname,
            @QueryParam("sex") String sex,
            @QueryParam("min-age") String minAge,
            @Context UriInfo uriInfo
    ) {

        Map<String, ?> ids = new HashMap<>();
        ids.put(Person.NAME_PK_COLUMN, name);
        ids.put(Person.SURNAME_PK_COLUMN, surname);

        return LinkRest.select(Person.class, config)
                // ... apply conditions
                .parent(Person.class, ids, Person.FRIENDS)
                .uri(uriInfo)
                .select();
    }
}
```

Of course, query parameters may be replaced with Cayenne expression.

**Comment by andrus** [comment]
this already works in Agrest
