### ISSUE TITLE
I'm looking for a way to fetch the relation key without loading of a relation.

### ISSUE THREAD

**Issue by alevshunov** [agrestio/agrest#539]
I have two entities like Game and Incident, and the relation is incident.game via incident.game_id FK (incident.game_id => game.id).
To fetch an incident with a game I do next: GET incident?include=game and agrest populate the response with the game_id field and the game object. Under the hood two sql requests are made, something like: select * from game ... and select * from incident .... 

But sometimes it make a sense for us to fetch only the game_id (FK of the relation) and avoid to execute extra sql request to improve the performance.
Is there a way to request the game_id without fetching/requesting the game at all. Something like: GET incident?include=game_id. 
Or maybe some configuration variable.

**Comment by andrus** [comment]
A canonical way of doing this from the protocol perspective would be `include=game.id`, but unfortunately Agrest would still run the second query in the backend. Cayenne itself actually has this optimization (if you need an id of a related object, it can be read from FK without the second query), but Agrest doesn't, and there's no easy way to add it. But eventually we will.

**Comment by andrus** [comment]
Closing this issue. Going to track the fix under #442
