### ISSUE TITLE
OpenAPI metadata - fields order

### ISSUE THREAD

**Issue by alevshunov** [agrestio/agrest#550]
By default metadata (/rest/meta/openapi.json) of agrest returns fields ordered by name. 
Will be nice to have ability to keep the order of these fields from db.

**Comment by andrus** [comment]
DB column order has no significance to Agrest (or the underlying Cayenne for that matter). Properties of response objects are ordered alphabetically by name in JSON. So OpenAPI model uses the same ordering. 

If there is a need for explicit alternative ordering, we need to discuss it in a wider context. I would like to see some examples of why that would be important, and where do we take it from.

**Comment by andrus** [comment]
Closing this for now. We'll reopen if our conclusions change.
