### ISSUE TITLE
AgRest own full-featured expression parser

### ISSUE THREAD

**Issue by stariy95** [agrestio/agrest#582]
The last part that is still require Cayenne is complex expressions. To fully decouple everything we should implement own full-featured parser. It still could be based on the Cayenne grammar for the max compatibility. 

There's already a working prototype with Cayenne backend switched to the new Expressions in the [5.x-expressions](https://github.com/agrestio/agrest/tree/5.x-expressions) branch. This implementation deprecates old code in the `io.agrest.exp` package and introduces `io.agrest.exp.parser`. 

Grammar file is here: [https://github.com/agrestio/agrest/blob/5.x-expressions/agrest-engine/src/main/jjtree/io/agrest/exp/parser/AgExpressionParser.jjt](https://github.com/agrestio/agrest/blob/5.x-expressions/agrest-engine/src/main/jjtree/io/agrest/exp/parser/AgExpressionParser.jjt)

**Comment by andrus** [comment]
`5.x-expressions` branch looks great. The approach is the best I can think of. Once we merge it, we can decide how much of the deprecated API we need to keep. For now a few comments:

* We need parser tests for all possible expressions
* (a micro-optimization) AND and OR operations should be "flattened" when appending more clauses kind of like `CompositeExp.and` and `CompositeExp.or` do.
