### ISSUE TITLE
How to configure the DataObject encoding / serialization ?

### ISSUE THREAD

**Issue by borgogelli** [agrestio/agrest#688]
I am using Agrest.io to port a Cayenne project to the cloud.
For simple CRUD operation, Agrest is great.
But I have also some complex business logic which returns one or more DataObjects.
So I'm triying to serialize them with the following code.

```
    @GET  
    @Path("hello")    
    public DataResponse<Provincia>  demo( ) throws IllegalConfigException {    	
    	 CayenneConn.open();  // initializes the dataContext
    	 Encoder encoder1 = GenericEncoder.encoder(); // same problem with that encoder
    	 Encoder encoder2 = DataResponseEncoder.defaultEncoder();
         return DataResponse.of( HttpStatus.OK, List.of(Provincia.getFirst()).encoder(encoder2).build(); 
    }
```

The result is not the one expected. I would like to serialize a simple DataObject which represent a db record (without following any external relationships). Where am I going wrong? 

```
 
{"data":[{"objectId":{"entityName":"Provincia","key":null,"temporary":false,"idSnapshot":
{"IDPROVINCIA":"054"},"replacementIdAttached":false,"replacementIdMap":
{}},"persistenceState":3,"snapshotVersion":-9223372036854775235,"denominazione":"Perugia","idprovincia":"054","idregione":"1
0","sigla":"PG","comuneArray":null,"sedeInailArray":null,"sededmagArray":null,"sedeenpalsArray":null,"sedeinpdaiArray":null,"sed
einpdapArray":null,"sedeinpsArray":null,"toRegione":null,"trento":false,"objectContext":
{"validatingObjectsOnCommit":true,"delegate":null,"objectStore":{"context":
{"validatingObjectsOnCommit":true,"delegate":null,"objectStore":{"context":
{"validatingObjectsOnCommit":true,"delegate":null,"objectStore":{"context":
{"validatingObjectsOnCommit":true,"delegate":null,"objectStore":
................. many many more...... 
```
I would like to returns only a db record, like:
```
{
"denominazione":"Perugia",
"idprovincia":"054",
"idregione":"10",
"sigla":"PG"
}
```

**Comment by andrus** [comment]
@borgogelli , you have two options here:

1. Don't use Agrest on this particular endpoint, only use Cayenne and do manual JSON generation (e.g. via DTO classes)
2. Customize the Agrest pipeline with `AgEntityOverlay`'s - https://agrest.io/docs/5.x/framework/#entity-overlays

I guess the former is mostly self-explanatory. The latter allows to preserve all the good stuff in Agrest (including encoders), but change a lot of things (entity structure, entity fetch algorithm, etc.). E.g. to provide custom objects instead of using a generated Cayenne query, you can use a few flavors of `AgEntityOverlay.dataResolver(..)` method

**Comment by borgogelli** [comment]
I would have expected that it would be possible to serialize only the attributes of a single Cayenne DataObject (without following
any relationships or serializing the entire data context)

My doubt arose from what I had read [here](https://stackoverflow.com/questions/52876771/how-to-convert-model-to-json):
_"Agrest supports **rule-based** serialization of Cayenne object graphs to JSON"_

So I will go with the solution 2) and json bindig (JSR 367)

Thank you.

**Comment by andrus** [comment]
> I would have expected that it would be possible to serialize only the attributes of a single Cayenne DataObject (without following any relationships or serializing the entire data context)

It is kinda possible, just no easy API to do that, as DataObject encoders are created dynamically and require a bunch of Agrest-specific context. So a DTO approach is the most pragmatic way about it.
